"""revoked module

Revision ID: 978ee3e24558
Revises: 87335d4a61eb
Create Date: 2026-09-20 01:39:45.158462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978ee3e24558'
down_revision: Union[str, Sequence[str], None] = '87335d4a61eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revoked', 'user_id')
    # ### end Alembic commands ###
