"""add sicial account

Revision ID: 27027a0672fb
Revises: 09b21148462c
Create Date: 2026-09-29 09:58:29.109100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27027a0672fb'
down_revision: Union[str, Sequence[str], None] = '09b21148462c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_Account', sa.Column('business_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_Account', 'business_id')
    # ### end Alembic commands ###
