"""add sicial account

Revision ID: 38fe326a198b
Revises: 27027a0672fb
Create Date: 2026-09-29 11:49:20.595479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fe326a198b'
down_revision: Union[str, Sequence[str], None] = '27027a0672fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_Account', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'social_Account', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'social_Account', type_='foreignkey')
    op.alter_column('social_Account', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
